"""Sync models with database

Revision ID: 952d467b92d2
Revises: 
Create Date: 2025-12-16 17:27:54.917394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '952d467b92d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_activity_log_created'))
        batch_op.drop_index(batch_op.f('idx_activity_log_project'))
        batch_op.drop_index(batch_op.f('idx_activity_log_task'))
        batch_op.drop_index(batch_op.f('idx_activity_log_user'))

    op.drop_table('activity_log')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_attachments_task'))
        batch_op.drop_index(batch_op.f('idx_attachments_user'))
        batch_op.create_index(batch_op.f('ix_attachments_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_comments_parent'))
        batch_op.drop_index(batch_op.f('idx_comments_task'))
        batch_op.drop_index(batch_op.f('idx_comments_user'))
        batch_op.create_index(batch_op.f('ix_comments_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Unique membership identifier',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               comment='Project ID',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               comment='User ID',
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'MEMBER', 'VIEWER', name='user_role'),
               comment='Member role in project',
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::user_role"))
        batch_op.alter_column('joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Membership creation timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_project_members_project'))
        batch_op.drop_index(batch_op.f('idx_project_members_user'))
        batch_op.drop_constraint(batch_op.f('project_members_project_id_user_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_project_user', ['project_id', 'user_id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Unique project identifier',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment='Project name',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment='Project description',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='project_status'),
               comment='Project status',
               existing_nullable=False,
               existing_server_default=sa.text("'PLANNING'::project_status"))
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False,
               comment='Project color code (hex)',
               existing_server_default=sa.text("'#3B82F6'::character varying"))
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(),
               comment='Project owner user ID',
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               comment='Project start date',
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               comment='Project target end date',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Project creation timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Last modification timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_projects_owner'))
        batch_op.drop_index(batch_op.f('idx_projects_status'))
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Unique task identifier',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               comment='Task title/summary',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment='Task detailed description (supports markdown)',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'ARCHIVED', name='task_status'),
               comment='Task current status',
               existing_nullable=False,
               existing_server_default=sa.text("'TODO'::task_status"))
        batch_op.alter_column('priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='task_priority'),
               comment='Task priority level',
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::task_priority"))
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               comment='Project ID this task belongs to',
               existing_nullable=False)
        batch_op.alter_column('assignee_id',
               existing_type=sa.UUID(),
               comment='User ID assigned to this task',
               existing_nullable=True)
        batch_op.alter_column('reporter_id',
               existing_type=sa.UUID(),
               comment='User ID who created this task',
               existing_nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Position within status column (for ordering)',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Task deadline',
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Completion timestamp',
               existing_nullable=True)
        batch_op.alter_column('estimated_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Estimated time in hours',
               existing_nullable=True)
        batch_op.alter_column('actual_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Actual time spent in hours',
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment='Task tags/labels (JSON array)',
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Task creation timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Last modification timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_tasks_assignee'))
        batch_op.drop_index(batch_op.f('idx_tasks_due_date'))
        batch_op.drop_index(batch_op.f('idx_tasks_position'))
        batch_op.drop_index(batch_op.f('idx_tasks_priority'))
        batch_op.drop_index(batch_op.f('idx_tasks_project'))
        batch_op.drop_index(batch_op.f('idx_tasks_reporter'))
        batch_op.drop_index(batch_op.f('idx_tasks_status'))
        batch_op.drop_index(batch_op.f('idx_tasks_tags'), postgresql_using='gin')
        batch_op.create_index('idx_task_project_status_position', ['project_id', 'status', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='Unique user identifier',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               comment='User email address',
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Bcrypt hashed password',
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               comment='User full name',
               existing_nullable=False)
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Profile picture URL',
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'MEMBER', 'VIEWER', name='user_role'),
               comment='User role for permissions',
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::user_role"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Account enabled/disabled',
               existing_server_default=sa.text('true'))
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Email verification status',
               existing_server_default=sa.text('false'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Account creation timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Last modification timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last login timestamp',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_users_active'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_role'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_active'), ['is_active'], unique=False)
        batch_op.alter_column('last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last login timestamp',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Last modification timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Account creation timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Email verification status',
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Account enabled/disabled',
               existing_server_default=sa.text('true'))
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'MEMBER', 'VIEWER', name='user_role'),
               comment=None,
               existing_comment='User role for permissions',
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::user_role"))
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Profile picture URL',
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='User full name',
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bcrypt hashed password',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='User email address',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique user identifier',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_id'))
        batch_op.drop_index('idx_task_project_status_position')
        batch_op.create_index(batch_op.f('idx_tasks_tags'), ['tags'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_tasks_reporter'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tasks_project'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_tasks_position'), ['project_id', 'status', 'position'], unique=False)
        batch_op.create_index(batch_op.f('idx_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_tasks_assignee'), ['assignee_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Last modification timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Task creation timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment=None,
               existing_comment='Task tags/labels (JSON array)',
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('actual_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Actual time spent in hours',
               existing_nullable=True)
        batch_op.alter_column('estimated_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Estimated time in hours',
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Completion timestamp',
               existing_nullable=True)
        batch_op.alter_column('due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Task deadline',
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Position within status column (for ordering)',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('reporter_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User ID who created this task',
               existing_nullable=False)
        batch_op.alter_column('assignee_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User ID assigned to this task',
               existing_nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Project ID this task belongs to',
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='task_priority'),
               comment=None,
               existing_comment='Task priority level',
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::task_priority"))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'ARCHIVED', name='task_status'),
               comment=None,
               existing_comment='Task current status',
               existing_nullable=False,
               existing_server_default=sa.text("'TODO'::task_status"))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Task detailed description (supports markdown)',
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Task title/summary',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique task identifier',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))
        batch_op.create_index(batch_op.f('idx_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_projects_owner'), ['owner_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Last modification timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Project creation timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Project target end date',
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Project start date',
               existing_nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Project owner user ID',
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True,
               comment=None,
               existing_comment='Project color code (hex)',
               existing_server_default=sa.text("'#3B82F6'::character varying"))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='project_status'),
               comment=None,
               existing_comment='Project status',
               existing_nullable=False,
               existing_server_default=sa.text("'PLANNING'::project_status"))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Project description',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Project name',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique project identifier',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_user', type_='unique')
        batch_op.drop_index(batch_op.f('ix_project_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))
        batch_op.create_unique_constraint(batch_op.f('project_members_project_id_user_id_key'), ['project_id', 'user_id'])
        batch_op.create_index(batch_op.f('idx_project_members_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_project_members_project'), ['project_id'], unique=False)
        batch_op.alter_column('joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Membership creation timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'MEMBER', 'VIEWER', name='user_role'),
               comment=None,
               existing_comment='Member role in project',
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::user_role"))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User ID',
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Project ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique membership identifier',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_comments_task_id'))
        batch_op.create_index(batch_op.f('idx_comments_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_comments_task'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_comments_parent'), ['parent_comment_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_task_id'))
        batch_op.create_index(batch_op.f('idx_attachments_user'), ['uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_attachments_task'), ['task_id'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('activity_log_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('activity_log_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('activity_log_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_log_pkey'))
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_activity_log_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_log_task'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_log_project'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_log_created'), ['created_at'], unique=False)

    # ### end Alembic commands ###
